apiVersion: v1
kind: Pod
metadata:
  name: portal-de-noticias
  labels:
    app: portal-noticias
spec:
  containers:
    - name: portal-conainer
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap
